# Import des templates de jobs pré-configurés
include:
  - project: o/infra/templates
    file: /gitlab-ci/includes/jobs.yaml

stages:
  - build
  - deploy
  - version
# Build docker image for private repository
build:private:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --build-arg HUGINN_IMAGE=git.octree.ch:4567/o/huginn-lite/releases:latest --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE/huginn-octree:${CI_COMMIT_TAG:-latest} 

# Publish to dockerhub
build:publish:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: "$CI_COMMIT_TAG =~ /v.*$/"
  script:
    - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$DOCKERHUB_AUTH\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor \
          --context "$CI_PROJECT_DIR" \
          --dockerfile $CI_PROJECT_DIR/Dockerfile \
          --destination octree/huginn-lite:$TAG \
          --verbosity=error

# Update in jelastic env.
deploy:private:
  extends: .deployJelastic
  needs: ["build:private"]
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: "$CI_COMMIT_TAG =~ /v.*$/"
  environment:
    name: Prod Backend
    url: "https://huginn.octr.ee"

version:
  extends: .release